#pragma once

#include <openssl/evp.h>
#include <openssl/rand.h>
#include <array>

#include <iostream>

namespace prototype_functions {

    std::array<unsigned char, 32> generate_key();

    //This function is generated by AI
    void openssl_sanity_check();

}