#pragma once

#include <openssl/evp.h>
#include <openssl/rand.h>
#include <vector>
#include <array>

#include <iostream>

namespace prototype_functions {

    std::array<unsigned char, 16> generate_initialization_vector();
    std::array<unsigned char, 32> generate_key();

    std::vector<unsigned char> aes_encrypt(
    const std::vector<unsigned char>& plaintext,
    const std::array<unsigned char, 32>& key,  
    const std::array<unsigned char, 16>& iv    
    );
    std::vector<unsigned char> aes_decrypt(
    const std::vector<unsigned char>& ciphertext,
    const std::array<unsigned char, 32>& key,  
    const std::array<unsigned char, 16>& iv    
    
    );
    //This function is generated by AI
    void openssl_sanity_check();

}//chudmaxxed