#pragma once

#include <openssl/evp.h>
#include <openssl/rand.h>
#include <vector>
#include <array>

#include <iostream>

namespace prototype_functions {
    struct AesEncrypted {
        std::array<uint8_t, 16> iv;
        std::vector<uint8_t> ciphertext;
    };

    std::array<uint8_t, 16> generate_initialization_vector();
    std::array<uint8_t, 32> generate_key();

    std::vector<uint8_t> aes_encrypt(
    const std::vector<uint8_t>& plaintext,
    const std::array<uint8_t, 32>& key,  
    const std::array<uint8_t, 16>& iv    
    );
    std::vector<uint8_t> aes_decrypt(
    const std::vector<uint8_t>& ciphertext,
    const std::array<uint8_t, 32>& key,  
    const std::array<uint8_t, 16>& iv
    );
    //This function is generated by AI
    void openssl_sanity_check();

}