#include "cryptowrapper/aes256.h"

namespace prototype_functions {
    
    std::array<unsigned char, 32> generate_key() {
        std::array<unsigned char, 32> key{};
        
        RAND_bytes(key.data(), 32);
        return key;
    }

    //This function is ai generated by OpenAI chatgpt and will be removed
    void openssl_sanity_check()
    {
        std::cout << "OpenSSL version (macro): "
                << OPENSSL_VERSION_TEXT << '\n';

        std::cout << "OpenSSL version (runtime): "
                << OpenSSL_version(OPENSSL_VERSION) << '\n';
    }
}