#include "cryptowrapper/X25519.h"

namespace prototype_functions {


    //AI generated by openAI chatgpt
    X25519KeyPair x25519_generate_keypair() {
        X25519KeyPair kp{};

        EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_X25519, nullptr);
        if (!ctx) throw std::runtime_error("CTX alloc failed");

        if (EVP_PKEY_keygen_init(ctx) <= 0)
            throw std::runtime_error("keygen init failed");

        EVP_PKEY* pkey = nullptr;
        if (EVP_PKEY_keygen(ctx, &pkey) <= 0)
            throw std::runtime_error("keygen failed");

        size_t len = 32;
        EVP_PKEY_get_raw_private_key(pkey, kp.priv.data(), &len);
        EVP_PKEY_get_raw_public_key(pkey, kp.pub.data(), &len);

        EVP_PKEY_free(pkey);
        EVP_PKEY_CTX_free(ctx);

        return kp;
    }
    std::array<unsigned char, 32> x25519_shared_secret(
        const std::array<unsigned char, 32>& my_priv,
        const std::array<unsigned char, 32>& peer_pub
    ) {
        std::array<unsigned char, 32> secret{};

        EVP_PKEY* priv = EVP_PKEY_new_raw_private_key(
            EVP_PKEY_X25519, nullptr, my_priv.data(), 32);

        EVP_PKEY* pub = EVP_PKEY_new_raw_public_key(
            EVP_PKEY_X25519, nullptr, peer_pub.data(), 32);

        EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new(priv, nullptr);
        if (!ctx) throw std::runtime_error("derive ctx failed");

        if (EVP_PKEY_derive_init(ctx) <= 0)
            throw std::runtime_error("derive init failed");

        if (EVP_PKEY_derive_set_peer(ctx, pub) <= 0)
            throw std::runtime_error("set peer failed");

        size_t len = secret.size();
        if (EVP_PKEY_derive(ctx, secret.data(), &len) <= 0)
            throw std::runtime_error("derive failed");

        EVP_PKEY_free(priv);
        EVP_PKEY_free(pub);
        EVP_PKEY_CTX_free(ctx);

        return secret;
    }
}